### ISSUE TITLE
undefined method `pop' for nil:NilClass: connection_pool.rb:22:in `checkout'

### ISSUE THREAD

**Issue by christianmarth** [tompesman/push-core#32]
```
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/push-core-1.0.4/lib/push/daemon/delivery_handler.rb:36:in `handle_next_notification'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/push-core-1.0.4/lib/push/daemon/delivery_handler.rb:16:in `block (2 levels) in start'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/push-core-1.0.4/lib/push/daemon/delivery_handler.rb:14:in `loop'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/push-core-1.0.4/lib/push/daemon/delivery_handler.rb:14:in `block in start'
[2014-12-12 09:04:41] [ERROR] NoMethodError, undefined method `pop' for nil:NilClass: /usr/local/rvm/gems/ruby-1.9.3-p327/gems/push-core-1.0.4/lib/push/daemon/connection_pool.rb:22:in `checkout'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/push-core-1.0.4/lib/push/daemon/delivery_handler.rb:36:in `handle_next_notification'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/push-core-1.0.4/lib/push/daemon/delivery_handler.rb:16:in `block (2 levels) in start'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/push-core-1.0.4/lib/push/daemon/delivery_handler.rb:14:in `loop'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/push-core-1.0.4/lib/push/daemon/delivery_handler.rb:14:in `block in start'
```

When trying to run both GCM and APNS i get the following when starting the push daemon

**Comment by tompesman** [comment]
I need more information. I'm closing it for now. If you have more information I can look into it.

**Comment by biinari** [comment]
I had a similar problem (same symptoms, could be a different cause).

We have GCM and APNS configs set up with different app names. For some reason some of our GCM messages had the wrong app name set, so that meant it was looking in the APNS app for a GCM connection.

Hence, in the connection pool for the APNS app, looking for `@connections['Push::Daemon::GcmSupport::ConnectionGcm']` was returning nil.

Fix for us was to update the GCM messages to correct the app name:

```ruby
Push::MessageGCM.where(app: 'apns_app_name').update_all(app: 'gcm_app_name')
```
